#include <iostream>
#include <fstream>
#include <cstring>
#include <cstdint>

/*
 Y0 : AND
 Y1 : SHL
 Y0 Y1 : PPI
 Y2 : SC
 Y0 Y2 : AXO
 Y1 Y2 : AXI
 Y0 Y1 Y2 : PS
 Y3 : RX
 Y0 Y3 : TX
 Y1 Y3 : CO
 Y0 Y1 Y3 : OR
 Y2 Y3: XOR
 Y0 Y2 Y3 : IO
*/
/*#define RII 0b00000000000000000000000000000001
#define SPO 0b00000000100000000000000000000000 // 1
#define MMI 0b00000000010000000000000000000000 // 1
#define SPI 0b00000000001000000000000000000000 // 0
#define PPO 0b00000000000100000000000000000000 // 1
#define Y3  0b00000000000010000000000000000000  // 1
#define Y2  0b00000000000001000000000000000000  // 1
#define Y1  0b00000000000000100000000000000000  // 1
#define Y0  0b00000000000000010000000000000000  // 1
*/

#define SBC   0b100000000000000000000000
#define ROT   0b010000000000000000000000
#define NOFLG 0b001000000000000000000000
#define XI    0b000100000000000000000000
#define XO    0b000010000000000000000000
#define FPI   0b000001000000000000000000
#define SPI   0b000000100000000000000000
#define CI    0b000000010000000000000000

#define SPNOT 0b000000001000000000000000  // 0
#define ME    0b000000000100000000000000  // 1
#define MI    0b000000000010000000000000  // 1
#define RI    0b000000000001000000000000  // 1
#define II    0b000000000000100000000000  // 1
#define PE    0b000000000000010000000000  // 1
#define PI    0b000000000000001000000000  // 1
#define RS    0b000000000000000100000000  // 1

#define A3    0b000000000000000010000000 // 1
#define A2    0b000000000000000001000000 // 1
#define A1    0b000000000000000000100000 // 0
#define A0    0b000000000000000000010000 // 1
#define HI    0b000000000000000000001000 // 1
#define SPACT 0b000000000000000000000100 // 1
#define BI    0b000000000000000000000010 // 1
#define AI    0b000000000000000000000001 // 0

#define ADD A0
#define AND A1
#define OR A0|A1
#define XOR A2
#define SUB A0|A2
#define SPO A1|A2
#define BO A0|A1|A2
#define AO A3
#define RO A0|A3
#define PO A1|A3
#define ADC A0|A1|A3
#define CO A2|A3
#define SHL A0|A2|A3
#define SHR A1|A2|A3
#define FPO A0|A1|A2|A3


#define PIH PI|HI
#define PIL PI
#define POH PO|HI
#define POL PO
#define MIH MI|HI
#define MIL MI

void cpyArray(void *dst, int array[16])
{

        char *cdst = (char *)dst;
        for (int i = 0; i < 16; i++)
                cdst[i] = array[i];
}

#define Z0_C0_N0_PCM0 0
#define Z1_C0_N0_PCM0 1
#define Z0_C1_N0_PCM0 2
#define Z1_C1_N0_PCM0 3
#define Z0_C0_N1_PCM0 4
#define Z1_C0_N1_PCM0 5
#define Z0_C1_N1_PCM0 6
#define Z1_C1_N1_PCM0 7

enum Types{
        NOP=0,
        JMPI,
        JMPA,
        JMPR,
        BRNI,
        BRNA


};

struct Opcodes{
        std::string Name;
        unsigned int Microcode[16];
        unsigned char FlagDepender;
        Types t;
};




int main()
{
        Opcodes opcs[256]={

            {"NOP",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"JMP #",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME,RO|PIH,CO|PIL,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,JMPI},
{"JMP &",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME,RO|MIH,CO|MIL,RO|CI|ME,RO|PIH,CO|PIL,RS,RS,RS,RS,RS,RS,RS},0,JMPA},
{"JPC #",{POL|MIL,POH|MIH,RO|II|PE|ME,ME|PE,ME|PE,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},1,JMPI},
{"JPC &",{POL|MIL,POH|MIH,RO|II|PE|ME,ME|PE,ME|PE,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},1,JMPA},
{"JPZ #",{POL|MIL,POH|MIH,RO|II|PE|ME,ME|PE,ME|PE,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},2,JMPI},
{"JPZ &",{POL|MIL,POH|MIH,RO|II|PE|ME,ME|PE,ME|PE,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},2,JMPA},
{"JNC #",{POL|MIL,POH|MIH,RO|II|PE|ME,ME|PE,ME|PE,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},3,JMPI},
{"JNC &",{POL|MIL,POH|MIH,RO|II|PE|ME,ME|PE,ME|PE,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},3,JMPA},
{"JNZ #",{POL|MIL,POH|MIH,RO|II|PE|ME,ME|PE,ME|PE,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},4,JMPI},
{"JNZ &",{POL|MIL,POH|MIH,RO|II|PE|ME,ME|PE,ME|PE,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},4,JMPA},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADD A",{POL|MIL,POH|MIH,RO|II|PE|ME,ADD|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADD B",{POL|MIL,POH|MIH,RO|II|PE|ME,ADD|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADD A#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|BI|PE,ADD|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADD B#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|AI|PE,ADD|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADD SP#",{POL|MIL,POH|MIH,RO|II|PE|ME,BO|CI,AO|XI,RO|BI|PE,SPO|AI,ADD|SPI|NOFLG,XO|AI,CO|BI,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADD FP#",{POL|MIL,POH|MIH,RO|II|PE|ME,BO|CI,AO|XI,RO|BI|PE,FPO|AI,ADD|FPI|NOFLG,XO|AI,CO|BI,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADD FP,SP#",{POL|MIL,POH|MIH,RO|II|PE|ME,BO|CI,AO|XI,RO|BI|PE,SPO|AI,ADD|FPI|NOFLG,XO|AI,CO|BI,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADD &",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,ADD|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADD A&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|BI,ADD|AI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADD B&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|AI,ADD|BI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADD [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,ADD|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADD A[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|BI,ADD|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADD B[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|AI,ADD|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADD A{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|BI,ADD|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADD B{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|AI,ADD|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SUB A",{POL|MIL,POH|MIH,RO|II|PE|ME,SUB|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SUB B",{POL|MIL,POH|MIH,RO|II|PE|ME,SUB|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SUB A#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|BI|PE,SUB|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SUB B#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|AI|PE,SUB|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SUB SP#",{POL|MIL,POH|MIH,RO|II|PE|ME,BO|CI,AO|XI,RO|BI|PE,SPO|AI,SUB|SPI|NOFLG,XO|AI,CO|BI,RS,RS,RS,RS,RS,RS},0,NOP},
{"SUB FP#",{POL|MIL,POH|MIH,RO|II|PE|ME,BO|CI,AO|XI,RO|BI|PE,FPO|AI,SUB|FPI|NOFLG,XO|AI,CO|BI,RS,RS,RS,RS,RS,RS},0,NOP},
{"SUB FP,SP#",{POL|MIL,POH|MIH,RO|II|PE|ME,BO|CI,AO|XI,RO|BI|PE,SPO|AI,SUB|FPI|NOFLG,XO|AI,CO|BI,RS,RS,RS,RS,RS,RS},0,NOP},
{"SUB &",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,SUB|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SUB A&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|BI,SUB|AI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SUB B&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|AI,SUB|BI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SUB [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,SUB|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SUB A[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|BI,SUB|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SUB B[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|AI,SUB|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SUB A{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|BI,SUB|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SUB B{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|AI,SUB|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADC A",{POL|MIL,POH|MIH,RO|II|PE|ME,ADC|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADC B",{POL|MIL,POH|MIH,RO|II|PE|ME,ADC|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADC A#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|BI|PE,ADC|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADC B#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|AI|PE,ADC|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADC &",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,ADC|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADC A&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|BI,ADC|AI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADC B&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|AI,ADC|BI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADC [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,ADC|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADC A[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|BI,ADC|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADC B[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|AI,ADC|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADC A{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|BI,ADC|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ADC B{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|AI,ADC|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SBC A",{POL|MIL,POH|MIH,RO|II|PE|ME,SBC|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SBC B",{POL|MIL,POH|MIH,RO|II|PE|ME,SBC|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SBC A#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|BI|PE,SBC|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SBC B#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|AI|PE,SBC|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SBC &",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,SBC|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SBC A&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|BI,SBC|AI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SBC B&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|AI,SBC|BI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SBC [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,SBC|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SBC A[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|BI,SBC|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SBC B[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|AI,SBC|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SBC A{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|BI,SBC|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SBC B{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|AI,SBC|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"AND A",{POL|MIL,POH|MIH,RO|II|PE|ME,AND|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"AND B",{POL|MIL,POH|MIH,RO|II|PE|ME,AND|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"AND A#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|BI|PE,AND|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"AND B#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|AI|PE,AND|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"AND &",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,AND|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"AND A&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|BI,AND|AI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"AND B&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|AI,AND|BI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"AND [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,AND|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"AND A[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|BI,AND|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"AND B[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|AI,AND|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"AND A{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|BI,AND|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"AND B{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|AI,AND|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"OR A",{POL|MIL,POH|MIH,RO|II|PE|ME,OR|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"OR B",{POL|MIL,POH|MIH,RO|II|PE|ME,OR|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"OR A#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|BI|PE,OR|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"OR B#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|AI|PE,OR|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"OR &",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,OR|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"OR A&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|BI,OR|AI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"OR B&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|AI,OR|BI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"OR [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,OR|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"OR A[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|BI,OR|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"OR B[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|AI,OR|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"OR A{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|BI,OR|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"OR B{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|AI,OR|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"XOR A",{POL|MIL,POH|MIH,RO|II|PE|ME,XOR|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"XOR B",{POL|MIL,POH|MIH,RO|II|PE|ME,XOR|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"XOR A#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|BI|PE,XOR|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"XOR B#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|AI|PE,XOR|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"XOR &",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,XOR|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"XOR A&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|BI,XOR|AI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"XOR B&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|AI,XOR|BI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"XOR [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,XOR|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"XOR A[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|BI,XOR|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"XOR B[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|AI,XOR|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"XOR A{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|BI,XOR|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"XOR B{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|AI,XOR|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"CMP",{POL|MIL,POH|MIH,RO|II|PE|ME,SUB,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"CMP A#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|BI|PE,SUB,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"CMP B#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|AI|PE,SUB,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"CMP A&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|BI,SUB,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"CMP B&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|AI,SUB,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"CMP A[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|BI,SUB,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"CMP B[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|AI,SUB,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"CMP A[&FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|CI|ME,RO|MIH,CO|MIL,RO|BI,SUB,RS,RS,RS,RS,RS,RS},0,NOP},
{"CMP B[&FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIH,FPO|MIL,RO|CI|ME,RO|MIH,CO|MIL,RO|AI,SUB,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHL4",{POL|MIL,POH|MIH,RO|II|PE|ME,SHL|AI,SHL|AI,SHL|AI,SHL|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHL4 &",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,SHL|AI,SHL|AI,SHL|AI,SHL|RI,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHL4 A&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|AI,SHL|AI,SHL|AI,SHL|AI,SHL|AI,RS,RS,RS,RS,RS},0,NOP},
{"SHL4 [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,SHL|AI,SHL|AI,SHL|AI,SHL|RI,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHL4 A[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|AI,SHL|AI,SHL|AI,SHL|AI,SHL|AI,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHL4 A{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|CI|ME,RO|MIH,CO|MIL,RO|AI,SHL|AI,SHL|AI,SHL|AI,SHL|AI,RS,RS,RS},0,NOP},
{"LD A#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|AI|PE,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"LD B#",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|BI|PE,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"LD A&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"LD B&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"LD A[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"LD B[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"LD A%",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|CI|ME,RO|MIH,CO|MIL,RO|AI,RS,RS,RS,RS,RS,RS},0,NOP},
{"LD B%",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|CI|ME,RO|MIH,CO|MIL,RO|BI,RS,RS,RS,RS,RS,RS},0,NOP},
{"LD A[&FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|CI|ME,RO|MIH,CO|MIL,RO|AI,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"LD B[&FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|CI|ME,RO|MIH,CO|MIL,RO|BI,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHL",{POL|MIL,POH|MIH,RO|II|PE|ME,SHL|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHL &",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,SHL|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHL A&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|AI,SHL|AI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHL [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,SHL|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHL A[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|AI,SHL|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHL A{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|CI|ME,RO|MIH,CO|MIL,RO|AI,SHL|AI,RS,RS,RS,RS,RS,RS},0,NOP},
{"ST A&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,AO|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ST B&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,BO|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ST A[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,AO|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ST B[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,BO|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ST A%",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|CI|ME,RO|MIH,CO|MIL,AO|RI,RS,RS,RS,RS,RS,RS},0,NOP},
{"ST B%",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|CI|ME,RO|MIH,CO|MIL,BO|RI,RS,RS,RS,RS,RS,RS},0,NOP},
{"ST A[&FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|CI|ME,RO|MIH,CO|MIL,AO|RI,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ST B[&FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|CI|ME,RO|MIH,CO|MIL,BO|RI,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ROL",{POL|MIL,POH|MIH,RO|II|PE|ME,SHL|ROT|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ROL &",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,SHL|ROT|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ROL A&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|AI,SHL|ROT|AI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ROL [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,SHL|ROT|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ROL A[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|AI,SHL|ROT|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ROL A{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|CI|ME,RO|MIH,CO|MIL,RO|AI,SHL|ROT|AI,RS,RS,RS,RS,RS,RS},0,NOP},
{"MOV A,B",{POL|MIL,POH|MIH,RO|II|PE|ME,AO|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"MOV B,A",{POL|MIL,POH|MIH,RO|II|PE|ME,BO|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"MOV SP,FP",{POL|MIL,POH|MIH,RO|II|PE|ME,SPO|FPI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"MOV FP,SP",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|SPI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"MOV A,SP",{POL|MIL,POH|MIH,RO|II|PE|ME,AO|SPI,SPO|MIH,RO|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"MOV A,FP",{POL|MIL,POH|MIH,RO|II|PE|ME,AO|FPI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"MOV SP,A",{POL|MIL,POH|MIH,RO|II|PE|ME,SPO|AI,SPO|MIH,RO|BI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"MOV FP,A",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHR4",{POL|MIL,POH|MIH,RO|II|PE|ME,SHR|AI,SHR|AI,SHR|AI,SHR|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHR4 &",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,SHR|AI,SHR|AI,SHR|AI,SHR|RI,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHR4 A&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|AI,SHR|AI,SHR|AI,SHR|AI,SHR|AI,RS,RS,RS,RS,RS},0,NOP},
{"SHR4 [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,SHR|AI,SHR|AI,SHR|AI,SHR|RI,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHR4 A[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|AI,SHR|AI,SHR|AI,SHR|AI,SHR|AI,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHR4 A{FP}",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|CI|ME,RO|MIH,CO|MIL,RO|AI,SHR|AI,SHR|AI,SHR|AI,SHR|AI,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHR",{POL|MIL,POH|MIH,RO|II|PE|ME,SHR|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHR &",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,SHR|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHR A&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|AI,SHR|AI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHR [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,SHR|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHR A[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|AI,SHR|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"SHR A[&FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|CI|ME,RO|MIH,CO|MIL,RO|AI,SHR|AI,RS,RS,RS,RS,RS,RS},0,NOP},
{"POP A",{POL|MIL,POH|MIH,RO|II|PE|ME,SPO|MIL,SPO|MIH,RO|AI,SPACT|SPNOT,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"POP B",{POL|MIL,POH|MIH,RO|II|PE|ME,SPO|MIL,SPO|MIH,RO|BI,SPACT|SPNOT,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"POPW AB",{POL|MIL,POH|MIH,RO|II|PE|ME,SPO|MIL,SPO|MIH,RO|BI,ME,RO|AI,SPACT|SPNOT,SPACT|SPNOT,RS,RS,RS,RS,RS,RS},0,NOP},
{"POPB &",{POL|MIL,POH|MIH,RO|II|PE|ME,SPO|MIL,SPO|MIH,RO|AI,POH|MIH,POL|MIL,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,AO|RI,SPACT|SPNOT,RS,RS,RS},0,NOP},
{"POPW &",{POL|MIL,POH|MIH,RO|II|PE|ME,SPO|MIL,SPO|MIH,RO|BI,ME,RO|XI,POH|MIH,POL|MIL|SPACT|SPNOT,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,XO|RI|ME,BO|RI,SPACT|SPNOT},0,NOP},
{"POPB [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,SPO|MIL,SPO|MIH,RO|CI,FPO|MIL,FPO|MIH,AO|RI,SPACT|SPNOT,RS,RS,RS,RS,RS,RS},0,NOP},
{"POPW [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,SPO|MIL,SPO|MIH,RO|CI,ME,RO|XI,FPO|MIL,FPO|MIH|SPACT|SPNOT,XO|RI|ME,CO|RI,SPACT|SPNOT,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ROR",{POL|MIL,POH|MIH,RO|II|PE|ME,SHR|ROT|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ROR &",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,SHR|ROT|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ROR A&",{POL|MIL,POH|MIH,RO|II|PE|ME,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|AI,SHR|ROT|AI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ROR [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,SHR|ROT|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ROR A[FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|AI,SHR|ROT|AI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"ROR A[&FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,FPO|MIL,FPO|MIH,RO|CI|ME,RO|MIH,CO|MIL,RO|AI,SHR|ROT|AI,RS,RS,RS,RS,RS,RS},0,NOP},
{"PSH A",{POL|MIL,POH|MIH,RO|II|PE|ME,SPACT,SPO|MIL,SPO|MIH,AO|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"PSH B",{POL|MIL,POH|MIH,RO|II|PE|ME,SPACT,SPO|MIL,SPO|MIH,BO|RI,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"PSHB #",{POL|MIL,POH|MIH,RO|II|PE|ME,SPACT,RO|CI|PE,SPO|MIL,SPO|MIH,CO|RI,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"PSHW #",{POL|MIL,POH|MIH,RO|II|PE|ME,SPACT,RO|CI|ME|PE,RO|XI|ME|PE,SPACT|SPO|MIH,SPO|MIL,CO|RI|ME,XO|RI,RS,RS,RS,RS,RS,RS},0,NOP},
{"PSHSW #",{POL|MIL,POH|MIH,RO|II|PE|ME,SPACT,RO|CI|ME|PE,RO|XI|ME|PE,SPACT|SPO|MIH,SPO|MIL,XO|RI|ME,CO|RI,RS,RS,RS,RS,RS,RS},0,NOP},
{"PSHB &",{POL|MIL,POH|MIH,RO|II|PE|ME,SPACT,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|CI,SPO|MIL,SPO|MIH,CO|RI,RS,RS,RS,RS,RS},0,NOP},
{"PSHW &",{POL|MIL,POH|MIH,RO|II|PE|ME,SPACT,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|CI|ME,RO|XI,SPI|SPO|MIH,SPO|MIL,CO|RI|ME,XO|RI,RS,RS,RS},0,NOP},
{"PSHSW &",{POL|MIL,POH|MIH,RO|II|PE|ME,SPACT,RO|CI|ME|PE,RO|MIH|PE,CO|MIL,RO|CI|ME,RO|XI,SPACT|SPO|MIH,SPO|MIL,XO|RI|ME,CO|RI,RS,RS,RS},0,NOP},
{"PSHB [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,SPACT,SPACT|FPO|MIH,FPO|MIL,RO|CI,SPO|MIL,SPO|MIH,CO|RI,RS,RS,RS,RS,RS,RS},0,NOP},
{"PSHW [FP]",{POL|MIL,POH|MIH,RO|II|PE|ME,SPACT,SPACT|FPO|MIH,FPO|MIL,RO|CI|ME,RO|XI,SPO|MIH,SPO|MIL,CO|RI|ME,XO|RI,RS,RS,RS,RS},0,NOP},
{"RTS",{POL|MIL,POH|MIH,RO|II|PE|ME,SPO|MIL,SPO|MIH,RO|PIL,ME,RO|PIH,SPACT|SPNOT,SPACT|SPNOT,PE,PE,RS,RS,RS,RS},0,NOP},
{"JSR #",{POL|MIL,POH|MIH,RO|II|PE|ME,SPACT,SPO|MIH|SPACT,SPO|MIL,POL|RI,ME,POH|RI,POH|MIH,POL|MIL,RO|CI|ME|PE,RO|PIH|PE,CO|PIL,RS,RS},0,BRNI},
{"BEQ #",{POL|MIL,POH|MIH,RO|II|PE|ME,ME|PE,ME|PE,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},2,BRNI},
{"BNE #",{POL|MIL,POH|MIH,RO|II|PE|ME,ME|PE,ME|PE,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},4,BRNI},
{"BCS #",{POL|MIL,POH|MIH,RO|II|PE|ME,ME|PE,ME|PE,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},1,BRNI},
{"BCC #",{POL|MIL,POH|MIH,RO|II|PE|ME,ME|PE,ME|PE,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},3,BRNI},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"",{POL|MIL,POH|MIH,RO|II|PE|ME,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},
{"HLT",{POL|MIL,POH|MIH,RO|II,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS,RS},0,NOP},


        };

/*
        0 - Normal
        1 - Carry
        2 - Zero
        3 - No Carry
        4 - No Zero
*/

Opcodes ucodes[16][256];
Opcodes reference[17];
                for(int j=0;j<256;j++){
                        //memcpy(&(ucodes[0][j].Microcode[0]),&(opcs[j].Microcode[0]),16*sizeof(unsigned int));
                        //std::cout<<ucodes[i][j].Microcode[2]<<" "<<opcs[j].Microcode[2]<<"\n";
                        if(opcs[j].FlagDepender==0){
                                memcpy(reference[opcs[j].t].Microcode,opcs[j].Microcode,16*sizeof(unsigned int));
                        }
                }

        for(int i=0;i<4;i++){
                for(int j=0;j<256;j++){
        
                        memcpy(&(ucodes[i][j].Microcode[0]),&(opcs[j].Microcode[0]),16*sizeof(uint32_t));
                        //if(opcs[j].FlagDepender!=0){
                                if(opcs[j].FlagDepender==0){
                                        memcpy(&(ucodes[i][j].Microcode[0]),&(opcs[j].Microcode[0]),16*sizeof(uint32_t));
                                        //memcpy(ucodes[i][j].Microcode,reference[opcs[j].t].Microcode,16*sizeof(uint32_t));
                                }
                                if((i&1)&&opcs[j].FlagDepender==1){
                                        memcpy(ucodes[i][j].Microcode,reference[opcs[j].t].Microcode,16*sizeof(uint32_t));
                                }
                                if((i&2)&&opcs[j].FlagDepender==2){
                                        memcpy(ucodes[i][j].Microcode,reference[opcs[j].t].Microcode,16*sizeof(uint32_t));
                                }
                                if(!(i&1)&&opcs[j].FlagDepender==3){
                                        memcpy(ucodes[i][j].Microcode,reference[opcs[j].t].Microcode,16*sizeof(uint32_t));
                                }
                                if(!(i&2)&&opcs[j].FlagDepender==4){
                                        memcpy(ucodes[i][j].Microcode,reference[opcs[j].t].Microcode,16*sizeof(uint32_t));
                                }

                        //}
                }
        }


        std::ofstream file1, file2, file3;
        file1.open("microcode1.bin", std::ios::binary);
        file2.open("microcode2.bin", std::ios::binary);
        file3.open("microcode3.bin", std::ios::binary);
        
        // file1<<"v2.0 raw\n ";
        // file2<<"v2.0 raw\n ";
        // file3<<"v2.0 raw\n ";
        for (int k = 0; k < 4; k++)
        {
                for (int i = 0; i < 256; i++)
                {
                        for (int j = 0; j < 16; j++)
                        {

                                unsigned int c1 = ( ucodes[k][i].Microcode[j] & 255);//^0b11011110;
                                unsigned int c2 = ((ucodes[k][i].Microcode[j] >> 8) & 255);//^0b11101111;
                                unsigned int c3 = ((ucodes[k][i].Microcode[j] >> 16) & 255);//^0b11101111;
                                
                                file1.write(reinterpret_cast<char *>(&c1), 1);
                                file2.write(reinterpret_cast<char *>(&c2), 1);
                                file3.write(reinterpret_cast<char *>(&c3), 1);
                        }
                        // if(k==0)
                        // printf("\n");
                }
        }
        
}
